Adriano Giudice
L1feIsGood/RefactoringTest pull request #17
Opened 2022-02-22 13:40 UTC by PrizrakNight

Осуществил рефакторинг UserService и жду дальнейшего фидбека.
Ожидаю услышать о недостатках и преимуществах решения.

Рефакторинг осуществлен согласно практикам чистого и тестируемого кода.
На рефакторинг суммарно ушло 55 минут.

2022-02-22 21:44 UTC, L1feIsGood requested changes
С архитектурной точки зрения рефакторинг удался, небольшие вопросы по конкретным реализациям, но это мелочи.
А вот с точки зрения продакшн кода выпускать нельзя. Чего не хватает? Это не призыв к действию, просто уточнение.

2022-02-22 21:44 UTC, L1feIsGood commented on LegacyApp/DefaultDateTimeService.cs
> +        public DateTime Now => DateTime.Now;
Опасный сахар, особенно для пропертей, по факту превращающий их в анонимные методы. 
Так и до 
public Guid Guid => Guid.NewGuid();
недалеко

2022-02-22 21:44 UTC, L1feIsGood commented on LegacyApp/ICreditLimitSetter.cs
> +    // Ее можно вынести в базовый абстрактный класс, где согласно принципу LSP (Liskov substitution principle)
А есть ли compile-time средства, позволяющие не допустить таких случаев? Какой вариант предпочтительней? Аргументы?

2022-02-22 21:44 UTC, L1feIsGood commented on LegacyApp/ICreditLimitSetterFactory.cs
> +        }
Существует ли решение, при котором не будет необходимости добавлять код в этот метод при появлении новой стратегии? Если да, то какие у нее плюсы/минусы?

2022-02-22 21:44 UTC, L1feIsGood commented on LegacyApp/UserService.cs
> +            if (_userValidator.IsValid(user) == false)
Не, ну серьезно? После этого кажется, что остальное решение откуда-то списано...
А если не нравится отрицание в условии, всегда можно инвертировать саму функцию

2022-02-22 21:44 UTC, L1feIsGood commented on LegacyApp/UserValidator.cs
> +        private readonly Regex _mailRegex = new Regex(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$");
Это уже лишнее. По условию задачи в бизнес логике все правильно.

2022-02-22 21:44 UTC, L1feIsGood commented on LegacyApp/UserValidator.cs
> +            if (_mailRegex.IsMatch(user.EmailAddress) == false)
Ну как так то

2022-02-22 21:44 UTC, L1feIsGood commented on LegacyApp/UserValidator.cs
> +            var age = (int)Math.Floor(ageDelta.TotalDays / 365);
А что об этом думает високосный год? Это я уже конечно докапываюсь, но из-за таких вещей бывает ракеты падают)

2022-02-23 05:19 UTC, PrizrakNight commented on LegacyApp/UserValidator.cs
> +            var age = (int)Math.Floor(ageDelta.TotalDays / 365);
Этот момент не учел, с этим соглашусь)

2022-02-23 05:24 UTC, PrizrakNight commented on LegacyApp/ICreditLimitSetterFactory.cs
> +        }
Для исправления данной ситуации можно использовать рефлексию (Получать в сборке все ICreditLimitSetter)
Но тогда потребуется добавить еще и свойство TargetClient (string), по которому будет выбираться стратегия.

Плюсы: Не надо больше изменять метод в фабрике.
Минусы: В производительности.

2022-02-23 05:34 UTC, PrizrakNight commented on LegacyApp/ICreditLimitSetter.cs
> +    // Ее можно вынести в базовый абстрактный класс, где согласно принципу LSP (Liskov substitution principle)
Есть средства c C#8, где добавили инструмент проверки на уровне IDE и компиляции проверка на nullable.

Например: 

public Client? Client - может быть Null (При использовании свойства без Null-Check будет ругаться компилятор)
public Client Client - не может быть Null. (Но через конструкцию null! все равно можно присвоить)

Из своего опыта скажу, что всегда нужно устанавливать проверки на Null значения в аргументах, это хорошая практика.

2022-02-23 05:36 UTC, PrizrakNight commented on LegacyApp/DefaultDateTimeService.cs
> +        public DateTime Now => DateTime.Now;
Не вижу ничего плохого в использовании =>.
Работал во многих проектах много лет, проблем с этим сахаром никогда не возникало.

2022-02-23 05:37 UTC, PrizrakNight commented on LegacyApp/UserValidator.cs
> +        private readonly Regex _mailRegex = new Regex(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$");
Посчитал нужным использовать именно Regex, т.к Email может быть некорректно построен.

2022-02-23 05:38 UTC, PrizrakNight commented on LegacyApp/UserValidator.cs
> +            if (_mailRegex.IsMatch(user.EmailAddress) == false)
Не понял вопроса.

2022-02-23 05:41 UTC, PrizrakNight commented on LegacyApp/UserService.cs
> +            if (_userValidator.IsValid(user) == false)
Это мой стиль кода, про стиль кода ничего в задании не обсуждалось, считаю этот вопрос странным.
По поводу "Решение откуда-то списано" - меня оскорбляет, т.к я потратил 55 минут личного времени и решил выполнить задание.

То, что я использую такой стиль когда, ни о чем не говорит.

2022-02-23 14:34 UTC, closed without merging