Рязанов Ярослав
L1feIsGood/RefactoringTest pull request #23
Opened 2022-04-13 13:39 UTC by n0throw

2022-04-13 14:13 UTC, L1feIsGood requested changes
Направление мыслей правильное, но, к сожалению, применяются неподходящие инструменты. Из-за это появляется подозрение, что нет понимания принципа их работы и подходящей области применения. Если есть желание, можно доработать решение, предварительно ответив себе на поставленные вопросы.

2022-04-13 14:13 UTC, L1feIsGood commented on LegacyApp/UserService.cs
> +        private static void UpdateCreditLimit(ref User user)
1. Чем обусловлена статичность метода?
2. Для чего используется ref?

2022-04-13 14:13 UTC, L1feIsGood commented on LegacyApp/UserService.cs
> +            using var userCreditService = new UserCreditServiceClient();
Какую функцию выполняет оператор using, и что произойдет с объектом при обращении к нему в строках ниже? Какой lifetime scope у userCreditService в данном случае?

2022-04-13 14:13 UTC, L1feIsGood commented on LegacyApp/ValidateNewUser.cs
> +public static class ValidateNewUser
Не совсем понимаю одержимость статикой в решении) Как mock-ать UserService при статических зависимостях? Чем полезна возможность mock-ать зависимости?

2022-04-14 06:26 UTC, n0throw commented on LegacyApp/UserService.cs
> +        private static void UpdateCreditLimit(ref User user)
В планах было класс User заменить на record struct, только потом внимательно прочитал задание ("отрефакторить класс UserService") - ответ на второй вопрос.

2022-04-15 07:02 UTC, closed without merging