Refactoring by Bologov Alexander
L1feIsGood/RefactoringTest pull request #24
Opened 2022-05-16 18:24 UTC by AlexBite

#### Что сделано
- Уменьшена связность модулей
    - Из UserService выделен UserFactory, ответственный за создание пользователя
    - switch-case получения кредитного лимита заменён на фабрику - `CreditLimitProviderFactory`, получение лимита осуществляется через `ICreditLimitProvider`
- Улучшен код-стайл (именований условий, вынос константных значений)
- В UserService добавлен конструктор с IUserFactory для возможности использовать агрегацию вместо композиции (например для написания тестов)

2022-05-16 20:40 UTC, L1feIsGood requested changes
В целом неплохо, но есть спорные моменты, если есть желание можно поправить/объяснить решения

2022-05-16 20:40 UTC, L1feIsGood commented on LegacyApp/Services/CreateUserParams.cs
> +        public bool IsValid()
Как-то не совсем укладывается в голове валидация в классе с названием Params. Интуиция подсказывает, что это будет простой POCO без особых ответственностей. 
Для внешнего наблюдателя возникают некоторые вопросы, наличие которых говорит о неудачном проектировании:
Почему этим не занимается отдельная сущность-валидатор?
Как мокать эту логику для тестирования?
Чья валидность проверяется в методе? Параметров? Юзера? Создания юзера?

2022-05-16 20:40 UTC, L1feIsGood commented on LegacyApp/Services/CreditLimit/BaseCreditLimitProvider.cs
> +        public abstract int? GetCreditLimit(string firstName, string surname, DateTime dateOfBirth);
Действительно ли есть нужда в этом абстрактном родителе? Просто чтобы хранить одну зависимость для потомков? Что будет, если появится потомок с дополнительной зависимостью? Выглядит как оверинжиниринг, но право на существование, конечно, имеет

2022-05-16 20:40 UTC, L1feIsGood commented on LegacyApp/Services/CreditLimit/CreditLimitProviderFactory.cs
> +    }
Вот тут неплохо. Вопрос со звездочкой: можно ли избавиться от свича и в дальнейшем при появлении новых провайдеров не добавлять новый кейс? Если да, то как, какие плюсы/минусы?

2022-05-16 20:40 UTC, L1feIsGood commented on LegacyApp/Services/CreateUserParams.cs
> +            const int minAge = 21;
В чем отличие объявления константы внутри метода и внутри класса? Есть ли в каком-то из вариантов негативный эффект?

2022-05-16 20:40 UTC, L1feIsGood commented on LegacyApp/Services/IUserCreditService.cs
> +    }
Это какая-то забывашка?

2022-05-16 20:40 UTC, L1feIsGood commented on LegacyApp/Services/UserFactory.cs
> +            const int minCreditLimit = 500;
Похожий вопрос выше.

2022-05-16 20:40 UTC, L1feIsGood commented on LegacyApp/Services/UserFactory.cs
> +                return null;
Непонятно, почему в лимит провайдер переехала только половина логики с лимитом.

2022-05-16 20:40 UTC, L1feIsGood commented on LegacyApp/Services/UserService.cs
> +        }
Ну для написания тестов одного IUserFactory будет маловато, по сути UserFactory заменил собой половину UserService и кажется лишним, все его зависимости вполне могли быть внедрены напрямую сюда

2022-05-18 15:19 UTC, AlexBite commented on LegacyApp/Services/CreateUserParams.cs
> +        public bool IsValid()
Не укладывался по времени. В целом согласен, такой вариант может запутать с точки зрения пользователя. Нужно вынести отдельный класс - валидатор CreateUserParams и использовать его в UserFactory.

2022-05-18 15:31 UTC, AlexBite commented on LegacyApp/Services/CreditLimit/BaseCreditLimitProvider.cs
> +        public abstract int? GetCreditLimit(string firstName, string surname, DateTime dateOfBirth);
Класс создавался только для хранения единственной ответственности. Возможно это овер-инжиниринг. Если смущает, то можно избавиться от абстрактного класса.

Если появится потомок с дополнительной зависимостью, то можно рассмотреть следующие варианты:
1) Добавить эту зависимость, как обязательную для абстрактного класса (но это плохо из-за наличия обязательной для иницализации зависимости, которую используют только один потомок)
2) Избавить от абстрактного класса и использовать только интерфейс (что лучше для текущей архитектуре)

2022-05-18 15:35 UTC, AlexBite commented on LegacyApp/Services/CreditLimit/CreditLimitProviderFactory.cs
> +    }
Можно воспользоваться plugin pattern и подгружать LimitProvider'ы через assembly.

2022-05-18 15:40 UTC, AlexBite commented on LegacyApp/Services/CreateUserParams.cs
> +            const int minAge = 21;
Объявление в методе не засоряет скоуп класса, легче читается.

Негативных эффектов вроде нет ни в каком из вариантов с точки зрения работы кода.

2022-05-18 15:52 UTC, AlexBite commented on LegacyApp/Services/IUserCreditService.cs
> +    }
Что именно? =)

2022-05-18 15:53 UTC, AlexBite commented on LegacyApp/Services/UserFactory.cs
> +            const int minCreditLimit = 500;
Ответил https://github.com/L1feIsGood/RefactoringTest/pull/24#discussion_r876056577

2022-05-18 15:55 UTC, AlexBite commented on LegacyApp/Services/UserFactory.cs
> +                return null;
Посчитал, что проверка кредитного лимита - это только часть бизнес логики для добавления пользователей. Возможно в других местах, при расширении кодовой базы, нам эта логика будет не нужна.

2022-05-18 15:56 UTC, AlexBite commented on LegacyApp/Services/UserService.cs
> +        }
UserService на практике оказываются огромными и трудно поддерживаемыми. IUserFactory был сделан на перспективу, чтобы UserService сильно не толстел по кол-ву строк кода и был легко читаемым/поддерживаемым.

2023-06-06 11:36 UTC, closed without merging