Рефакторинг legacy кода by Koichi-hub (Тимур Давыдов)
L1feIsGood/RefactoringTest pull request #39
Opened 2023-06-24 19:34 UTC by Koichi-hub

2023-06-24 23:43 UTC, L1feIsGood requested changes
Хорошо, что раскиданы файлы по логическим папкам. Присутствуют первые шаги рефакторинга, к сожалению не доведен до конца. Также есть пара ошибок, если есть желание, можно исправить.

2023-06-24 23:43 UTC, L1feIsGood commented on LegacyApp/Repositories/ClientRepository.cs
> +                        Type = (ClientType)int.Parse(reader["Type"].ToString()),
А откуда инфа, что в базе есть поле Type?

2023-06-24 23:43 UTC, L1feIsGood commented on LegacyApp/Services/UserService.cs
> +        public bool AddUser(string firstName, string surname, string email, DateTime dateOfBirth, int clientId)
Изменив название переменной firName вы нарушили обратную совместимость. По условию задачи этот код является частью более масштабной системы, в которой метод может и будет вызываться с использованием named parameters. По условию задачи рефакторинг не должен привести к поломке вызывающего кода.

2023-06-24 23:43 UTC, L1feIsGood commented on LegacyApp/Services/UserService.cs
> +        }
Extract method только первый шаг. Почему методы остались в этом классе? Почему они static?

2023-06-24 23:43 UTC, L1feIsGood commented on LegacyApp/Services/UserService.cs
> +        }
Extract method только первый шаг. Почему методы остались в этом классе? Почему они static?

2023-06-24 23:43 UTC, L1feIsGood commented on LegacyApp/Services/UserService.cs
> +            using (_userCreditService)
А что будет при выполнении
var userService = new UserService();
userService.AddUser("Name1", ...);
userService.AddUser("Name2", ...);
?

2023-06-24 23:43 UTC, L1feIsGood commented on LegacyApp/Services/UserService.cs
> +            IUserFactory userFactory = new UserFactory();
А можно как-то избавиться от аггрегации? Допустим, мы хотим иметь возможность мокать составляющие UserService для написания тестов.

2023-06-25 22:42 UTC, Koichi-hub commented on LegacyApp/Repositories/ClientRepository.cs
> +                        Type = (ClientType)int.Parse(reader["Type"].ToString()),
Это было ошибочное решение. Забыл, что это legacy, и что даже в рамках тестового предметную область менять нельзя 😅

2023-06-25 22:59 UTC, Koichi-hub commented on LegacyApp/Services/UserService.cs
> +            IUserFactory userFactory = new UserFactory();
Можно написать 2 конструктора с и без параметров. Это конечно не по `SRP`, `OCP`, но DI в этом legacy нету 😢

2023-06-25 23:07 UTC, Koichi-hub commented on LegacyApp/Services/UserService.cs
> +        public bool AddUser(string firstName, string surname, string email, DateTime dateOfBirth, int clientId)
Забыл о такой фиче в C# 🤔

2023-06-25 23:41 UTC, Koichi-hub commented on LegacyApp/Services/UserService.cs
> +        }
Эти методы можно переиспользовать для валидации сущности `User` (в legacy не используют `DTO` 😢). Поэтому имеет смысл вынести их в отдельный класс `UserValidation`
Забыл, что их можно вызывать через `this` 😅, просто в последнее время слишком много пишу на go 😹

2023-07-03 11:36 UTC, closed without merging